multi_tracker/detector/name: Detectron2
multi_tracker/detector/weights: detectron_simulation.pth
multi_tracker/detector/config: detectron_config.yaml
multi_tracker/tracker/name: ByteTrack
multi_tracker/tracker/config:  siammask_config.yaml
multi_tracker/tracker/weights:  siammask_model.pth
multi_tracker/input: /quad97/camera/image_raw
multi_tracker/visualize: true
multi_tracker/redetect_time: 2.0
multi_tracker/number_object: 4


multi_tracker/bytetrack/track_thresh: 0.5
multi_tracker/bytetrack/device: "gpu"
multi_tracker/bytetrack/track_buffer: 30
multi_tracker/bytetrack/match_thresh: 0.8
